# Generated by Django 5.2.9 on 2025-12-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentaddress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='apartmentaddress',
            name='longitude',
        ),
    ]
