# Generated by Django 5.2.9 on 2025-12-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_remove_apartmentaddress_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='apartments', to='apartments.amenity'),
        ),
        migrations.DeleteModel(
            name='ApartmentAmenity',
        ),
    ]
