# Generated by Django 5.2.9 on 2025-12-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_apartment_amenities_delete_apartmentamenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentpricing',
            name='currency',
            field=models.CharField(choices=[('GBP', 'British Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='GBP', max_length=10),
        ),
    ]
