# Generated by Django 5.2.9 on 2025-12-17 10:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_alter_apartmentpricing_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
