# Generated by Django 5.2.9 on 2025-12-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_alter_apartmentimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='apartments.apartment'),
        ),
    ]
