# Generated by Django 5.2.9 on 2025-12-17 13:26

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_alter_apartmentimage_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/c-dfb50e1bf783e237800c884befeee3/image/upload/v1/apartments/placeholder.jpg', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('room', 'Private Room'), ('entire_home', 'Entire Home'), ('studio', 'Studio'), ('villa', 'Villa')], default='apartment', max_length=50),
        ),
        migrations.DeleteModel(
            name='ApartmentImage',
        ),
    ]
