# Generated by Django 5.2.9 on 2025-12-17 13:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_apartment_image_apartment_is_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://console.cloudinary.com/app/c-dfb50e1bf783e237800c884befeee3/assets/media_library/folders/cd9602a7a4891371a4b171786c855042a9?view_mode=mosaic', max_length=255, null=True),
        ),
    ]
