# Generated by Django 5.2.9 on 2025-12-15 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('apartment_available', 'Apartment Available'), ('apartment_pending', 'Apartment Pending Approval'), ('apartment_approved', 'Apartment Approved'), ('apartment_rejected', 'Apartment Rejected'), ('system', 'System')], max_length=50)),
                ('target_audience', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('both', 'User & Admin')], max_length=10)),
                ('apartment_id', models.UUIDField(blank=True, null=True)),
                ('booking_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_admin_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
